mc_cores: 12


mcell_mc2d_K: 60
mcell_mc2d_T_edge: 0.001
mcell_mc2d_max_confu_deg: 4
mcell_mc2d_edge_asym: TRUE
mcell_mc2d_k_expand_inout_factor: NULL
mcell_mc2d_proj_blur: 0.02
mcell_mc2d_K_cellproj: 20


mcell_mc2d_height: 900
mcell_mc2d_width: 900
mcell_mc2d_legend_cex: 1.2

